# Generated by Django 4.1.5 on 2023-04-09 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='units',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='schedule',
            name='total_units',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CourseTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=10)),
                ('starting_time', models.CharField(default='00:00', max_length=10)),
                ('ending_time', models.CharField(default='00:00', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.course')),
            ],
        ),
    ]
