# Generated by Django 4.1.5 on 2023-04-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.IntegerField(default=8),
        ),
    ]
