# Generated by Django 4.1.7 on 2023-04-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedule_scheduleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
