# Generated by Django 4.1.7 on 2023-04-07 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_schedule_comments_schedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.cart'),
        ),
    ]
